In [8]:
import pandas as pd
from keras.models import Sequential
from keras.layers import *

In [9]:
training_data_df = pd.read_csv("sales_data_training_scaled.csv")
training_data_df.head()

,critic_rating,is_action,is_exclusive_to_us,is_portable,is_role_playing,is_sequel,is_sports,suitable_for_kids,total_earnings,unit_price
0,0.500000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.374714,1.0
1,0.833333,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.192425,0.5
2,0.333333,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.114852,0.5
3,0.833333,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.142452,0.0
4,0.666667,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.480682,1.0

In [10]:
X = training_data_df.drop('total_earnings', axis=1).values
Y = training_data_df[['total_earnings']].values

In [23]:
# Define the model
model = Sequential()
model.add(Dense(50, input_dim=9, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(1, activation='linear'))
model.compile(loss="mean_squared_error", optimizer="adam")

In [24]:
# Train the model
model.fit(X,Y,epochs=50,shuffle=True,verbose=2)

Epoch 1/50
 - 0s - loss: 0.0178
Epoch 2/50
 - 0s - loss: 0.0024
Epoch 3/50
 - 0s - loss: 0.0010
Epoch 4/50
 - 0s - loss: 5.2853e-04
Epoch 5/50
 - 0s - loss: 2.6491e-04
Epoch 6/50
 - 0s - loss: 1.6157e-04
Epoch 7/50
 - 0s - loss: 1.2664e-04
Epoch 8/50
 - 0s - loss: 9.7959e-05
Epoch 9/50
 - 0s - loss: 7.7247e-05
Epoch 10/50
 - 0s - loss: 7.8740e-05
Epoch 11/50
 - 0s - loss: 6.7958e-05
Epoch 12/50
 - 0s - loss: 4.5473e-05
Epoch 13/50
 - 0s - loss: 3.8884e-05
Epoch 14/50
 - 0s - loss: 3.5680e-05
Epoch 15/50
 - 0s - loss: 2.8212e-05
Epoch 16/50
 - 0s - loss: 2.8226e-05
Epoch 17/50
 - 0s - loss: 3.0552e-05
Epoch 18/50
 - 0s - loss: 3.3478e-05
Epoch 19/50
 - 0s - loss: 4.5568e-05
Epoch 20/50
 - 0s - loss: 3.1912e-05
Epoch 21/50
 - 0s - loss: 2.4934e-05
Epoch 22/50
 - 0s - loss: 3.7378e-05
Epoch 23/50
 - 0s - loss: 2.6178e-05
Epoch 24/50
 - 0s - loss: 1.9706e-05
Epoch 25/50
 - 0s - loss: 1.9773e-05
Epoch 26/50
 - 0s - loss: 1.8963e-05
Epoch 27/50
 - 0s - loss: 2.0989e-05
Epoch 28/50
 - 0s - loss: 1.9722e-05
Epoch 29/50
 - 0s - loss: 2.7128e-05
Epoch 30/50
 - 0s - loss: 1.9877e-05
Epoch 31/50
 - 0s - loss: 1.8207e-05
Epoch 32/50
 - 0s - loss: 1.7146e-05
Epoch 33/50
 - 0s - loss: 2.1754e-05
Epoch 34/50
 - 0s - loss: 2.8899e-05
Epoch 35/50
 - 0s - loss: 1.9469e-05
Epoch 36/50
 - 0s - loss: 2.6030e-05
Epoch 37/50
 - 0s - loss: 2.0087e-05
Epoch 38/50
 - 0s - loss: 2.1734e-05
Epoch 39/50
 - 0s - loss: 2.0689e-05
Epoch 40/50
 - 0s - loss: 2.1181e-05
Epoch 41/50
 - 0s - loss: 3.3891e-05
Epoch 42/50
 - 0s - loss: 2.3832e-05
Epoch 43/50
 - 0s - loss: 2.2583e-05
Epoch 44/50
 - 0s - loss: 1.7813e-05
Epoch 45/50
 - 0s - loss: 3.5058e-05
Epoch 46/50
 - 0s - loss: 2.7645e-05
Epoch 47/50
 - 0s - loss: 3.0053e-05
Epoch 48/50
 - 0s - loss: 2.7143e-05
Epoch 49/50
 - 0s - loss: 2.0864e-05
Epoch 50/50
 - 0s - loss: 2.4706e-05

In [25]:
# Load the separate test data set
test_data_df = pd.read_csv("sales_data_test_scaled.csv")
test_data_df.head()

,critic_rating,is_action,is_exclusive_to_us,is_portable,is_role_playing,is_sequel,is_sports,suitable_for_kids,total_earnings,unit_price
0,0.500000,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.799179,1.0
1,0.166667,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.157502,1.0
2,0.500000,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.189704,1.0
3,0.666667,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.392233,0.0
4,0.000000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.215464,1.0

In [26]:
X_test = test_data_df.drop('total_earnings', axis=1).values
Y_test = test_data_df[['total_earnings']].values

In [27]:
test_error_rate = model.evaluate(X_test, Y_test, verbose=0)
print("The mean squared error (MSE) for the test data set is: {}".format(test_error_rate))

The mean squared error (MSE) for the test data set is: 9.037367592100054e-05

In [28]:
# Save the model to disk
model.save("trained_model.h5")
print("Model saved to disk.")

Model saved to disk.